// const countries = [
//   {
//     name: "Wallis and Futuna",
//     capital: "Mata-Utu",
//     population: 11750,
//     flag: "https://flagcdn.com/wf.svg",
//     id: 1,
//      like: "https://www.svgrepo.com/show/407319/red-heart.svg",
//     basket: "https://www.svgrepo.com/show/509029/basket.svg",
//     more: "https://www.svgrepo.com/show/497332/more-circle.svg",
//   },
//   {
//     name: "Iceland",
//     capital: "Reykjavik",
//     population: 366425,
//     flag: "https://flagcdn.com/is.svg",
//     id: 2,
//   },
//   {
//     name: "Luxembourg",
//     capital: "Luxembourg",
//     population: 632275,
//     flag: "https://flagcdn.com/lu.svg",
//     id: 3,
//   },
//   {
//     name: "Mali",
//     capital: "Bamako",
//     population: 20250834,
//     flag: "https://flagcdn.com/ml.svg",
//     id: 4,
//   },
//   {
//     name: "Comoros",
//     capital: "Moroni",
//     population: 869595,
//     flag: "https://flagcdn.com/km.svg",
//     id: 5,
//   },
//   {
//     name: "Australia",
//     capital: "Canberra",
//     population: 25687041,
//     flag: "https://flagcdn.com/au.svg",
//     id: 6,
//   },
//   {
//     name: "Estonia",
//     capital: "Tallinn",
//     population: 1331057,
//     flag: "https://flagcdn.com/ee.svg",
//     id: 7,
//   },
//   {
//     name: "Canada",
//     capital: "Ottawa",
//     population: 38005238,
//     flag: "https://flagcdn.com/ca.svg",
//     id: 8,
//   },
//   {
//     name: "Belarus",
//     capital: "Minsk",
//     population: 9398861,
//     flag: "https://flagcdn.com/by.svg",
//     id: 9,
//   },
//   {
//     name: "Guyana",
//     capital: "Georgetown",
//     population: 786559,
//     flag: "https://flagcdn.com/gy.svg",
//     id: 10,
//   },
// ];

const countrys = [
  {
    name: "Germany",
    capital: "Berlin",
    population: 81770900,
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
  {
    name: "Canada",
    capital: "Ottawa",
    population: 38005238,
    flag: "https://flagcdn.com/ca.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
  {
    name: "Luxembourg",
    capital: "Luxembourg",
    population: 632275,
    flag: "https://flagcdn.com/lu.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
  {
    name: "Mali",
    capital: "Bamako",
    population: 20250834,
    flag: "https://flagcdn.com/ml.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
  {
    name: "Comoros",
    capital: "Moroni",
    population: 869595,
    flag: "https://flagcdn.com/km.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
  {
    name: "Australia",
    capital: "Canberra",
    population: 25687041,
    flag: "https://flagcdn.com/au.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
  {
    name: "Iceland",
    capital: "Reykjavik",
    population: 366425,
    flag: "https://flagcdn.com/is.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
  {
    name: "Wallis and Futuna",
    capital: "Mata-Utu",
    population: 11750,
    flag: "https://flagcdn.com/wf.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
  {
    name: "Belarus",
    capital: "Minsk",
    population: 9398861,
    flag: "https://flagcdn.com/by.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
  {
    name: "Guyana",
    capital: "Georgetown",
    population: 786559,
    flag: "https://flagcdn.com/gy.svg",
    like: "https://www.svgrepo.com/show/407319/red-heart.svg",
    basket: "https://www.svgrepo.com/show/509029/basket.svg",
    more: "https://www.svgrepo.com/show/497332/more-circle.svg",
  },
];
